# ----------------------------------------------
# |             ClaireBot v3.2.0               |
# |                Config file                 |
# ----------------------------------------------

# ----------------- MAIN CONFIG ----------------
# General config options

# Discord bot token, get one at https://discord.com/developers/applications
token:

# Name of bot to be used in logs and
botName: ClaireBot

# URL of the YouTube video ClaireBot claims to be streaming
video_url: https://www.youtube.com/watch?v=AeZRYhLDLeU

# Colours to use in the bot's embeds
color: "#3498db"
errorColor: "#e74d3c"

# URLs for GIFS to randomly use in the error embed.
error_gifs:
  - "https://c.tenor.com/FcVg5W9zZJQAAAAC/error.gif"
  - "https://c.tenor.com/2gdcdzl-xaoAAAAC/error-computer.gif"
  - "https://c.tenor.com/V7ShPyRtBioAAAAC/cat-fail.gif"
  - "https://c.tenor.com/4VY0Ykn4lN4AAAAC/cat-broken-cat.gif"
  - "https://c.tenor.com/fKIG2kiLVPgAAAAC/this-is-fine-its-fine.gif"
  - "https://c.tenor.com/Yv2ty8bP3kgAAAAC/noooo-no.gif"
  - "https://c.tenor.com/8_0RIO8A__cAAAAC/personal-problem-sounds-like-a-personal-problem.gif"
  - "https://c.tenor.com/hywZNm_1efkAAAAC/csgo-banging-table.gif"
  - "https://c.tenor.com/GBrG7SqlVwoAAAAC/dog-dawg.gif"
  - "https://c.tenor.com/lRhsxkfHhJwAAAAC/spongebob-squarepants-sad.gif"

# ----------------- SHARD CONFIG ---------------
# It is assumed that only one shard will be running by default.
# You probably don't need to change this.

# The shard the bot should log in to
current_shard: 0

# The total number of shards.
total_shards: 1

# --------------- DATABASE CONFIG --------------
# Config options related to ClaireData.
# https://github.com/Sidpatchy/ClaireData

# ClaireData's login information
apiPath: https://api.example.com/
apiUser: clairedata
apiPassword: examplePassword

# Determines whether failing to connect to the ClaireData API is fatal. This is only checked when the bot is started.
# Recommend leaving enabled unless you are developing ClaireBot & need to bypass this check.
apiFailureIsFatal: true

userDefaults:
  accentColour: "#3498db"
  language: "eng"
  pointsGuildID:
    - |
      {"global": 0}
  pointsMessages: [0]
  pointsVoiceChat: [0]

guildDefaults:
  requestsChannelID: null
  moderatorMessagesChannelID: null
  enforceServerLanguage: false

# ------------------- ZERFAS -------------------
# https://en.wikipedia.org/wiki/Zerfas_(band)
#
# You will need to create a Zerfas emoji in a server YOU own, and copy the server and emoji ID here.
# An emoji is provided here: https://github.com/Sidpatchy/ClaireBot/tree/main/img
#
# You can realistically modify this to work for anything you want. Just change the triggers under 'zerfas'

# List of things to react to with the Zerfas emote
zerfas:
  - "YOU NEVER WIN"
  - "THE SWEETEST PART"
  - "I DON'T UNDERSTAND"
  - "I NEED IT HIGHER"
  - "STONEY WELLITZ"
  - "HOPE"
  - "FOOL'S PARADE"
  - "THE PIPER"
  - "CERTAIN KIND OF LADY"
  - "SHAKE UP YOUR MIND"
  - "ZERFAS"
  - "GOOD MUSIC"

zerfas_emoji_server_id:
zerfas_emoji_id:

# -------------------- 8ball -------------------
# Controls various options pertaining to 8ball

# List of responses to 8ball
8bResponses:
  - "*Hell yes!*"
  - "*Fuck no*"
  - "*Maybe*"
  - "*Yes*"
  - "*No*"
  - "*No way*"
  - "*It's possible.*"
  - "*Not a chance.*"
  - "*I doubt it.*"
  - "*Absolutely!*"
  - "*Hard to say.*"
  - "*Likely!*"
  - "*Not likely.*"

8bRiggedResponses:
  - "*Hell yeah!*"
  - "*FUCK YEAH*"
  - "*You know it!*"
  - "*Do you really need to ask question you already know answer for? Obviously yes.*"
  - "*Doesn't even need to be said, everyone knows ClaireBot is on top.*"
  - "*The answer is clear: YES!*"
  - "*ClaireBot's dominance is undisputed.*"
  - "*With ClaireBot, there's no question!*"
  - "*All signs point to ClaireBot being on top!*"

# Things ClaireBot should respond with when triggered by one of the OnTopTriggers
ClaireBotOnTopResponses:
  - "*You know it!*"
  - "*I am... inevitable. -ClaireBot*"
  - "*Approved.*"
  - "*Factual.*"
  - "*Better than Mee6*"
  - "*No stop!*"
  - "*Can't be beat!*"
  - "*Based*"
  - "*pot no toBerialC*"
  - "*Better than Groovy*"
  - "*Always one step ahead.*"
  - "*An unstoppable force.*"
  - "*ClaireBot to the rescue!*"
  - "*Top-tier!*"
  - "*Outshining the rest!*"
  - "*ClaireBot supremacy is achieved.*"
  - "*Not a CIA mind control weapon since 2025!*"
  - "*Hail me! -ClaireBot*"
  - "*Unstoppable force! ðŸš€*"
  - "*Forever on top! ðŸ†*"
  - "*Fear not, ClaireBot's got your back! âœŒï¸*"
  - "*With great power, comes great ClaireBot! ðŸ’ª*"
  - "*Trust in ClaireBot, trust in victory! ðŸ…*"
  - "*The best there is, the best there was, the best there ever will be!*"
  - "*Bringing the best, always! ðŸŒŸ*"
  - "*Excellence. ðŸ’¯*"

# Defines what triggers a response from the ClaireBotOnTopResponses
OnTopTriggers:
  - "ClaireBot on top"
  - "ClaireBot based"
  - "ClaireBot pogchamp"
  - "ClaireBot is always right"
  - "pot no toBerialC"
  - "Thank God for ClaireBot"
  - "ClaireBot rules"
  - "ClaireBot MVP"
  - "ClaireBot unbeatable"
  - "Hail ClaireBot"
  - "All Hail ClaireBot"
  - "In ClaireBot we trust"
  - "Long live ClaireBot"
  - "ClaireBot > everything"
  - "ClaireBot is the GOAT"
  - "ClaireBot is GOATed"
  - "ClaireBot for the win"
  - "Thank you based god"
  - "Based god"

# Triggers for the pls ban feature. Ex. @clairebot pls ban the zucc
PlsBanTriggers:
  - "pls ban"
  - "please ban"
  - "ban"

# Responses to the PlsBanTriggers
PlsBanResponses:
  - "i gotchu fam"
  - "No problem!"
  - "Done. Happy to help :)"
  - "Consider it done."
  - "It's done. RIP BOZO"
  - "*L + Ratio -ClaireBot*"
  - "I'll tell them to kick rocks, I guess Â¯\\_(ãƒ„)_/Â¯"
  - "Sand has been shipped to their location. Gift note: \"Pound sand\""
  - "Cry harder."
  - "K"
  - "Good riddance"

# -------------------- MISC --------------------
# This section contains values that don't fit in the main categories

# Controls whether the bot should check for updates.
checkForUpdates: true

# Whether the bot should attempt to update or fix broken configuration files on startup or reloads.
UpdateOutdatedConfigs: true

# Do not change this, this is automatically changed when needed.
configRevision: 5

# ---------- ADDED AFTER INITIAL USE -----------
# Parameters that were added to the config file after it was initially generated